version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    executor:
      name: cypress/default
      node-version: '20.14.0'
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: 'npx wait-on@latest http://localhost:3000 && npx cypress run'
          start-command: 'npm run build && npm run start'
      - store_artifacts:
          path: cypress/videos
          destination: videos
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots

workflows:
  build:
    environment:
      CYPRESS_DEFAULT_EMAIL: $CYPRESS_DEFAULT_EMAIL
      CYPRESS_DEFAULT_PASSWORD: $CYPRESS_DEFAULT_PASSWORD
    jobs:
      - cypress-run
