version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    executor:
      name: cypress/default
      node-version: '20.14.0'

    steps:
      - checkout
      - cypress/install
      - run:
        name: "Build and Start Application"
        command: |
          npm run build
          npm run start &
      -run : 
        name: "Run Cypress with all CYPRESS_ env vars"
        command: |              
              env_string=$(printenv | grep '^CYPRESS_' | sed 's/^\(.*\)=\(.*\)$/\1=\2/' | paste -sd, -)
              echo "Using env: $env_string"
              npx wait-on@latest http://localhost:3000
              npx cypress run --env $env_string
     
workflows:
  build:
    jobs:
      - cypress-run
