version: 2.1
orbs:
  # "cypress-io/cypress@3" installs the latest published
  # version "s.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@3.x.y"
  # to lock the version and prevent unexpected CI changes.
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    docker:
      - image: cypress/browsers:node-20.16.0-chrome-127.0.6533.119-1-ff-129.0.1-edge-127.0.2651.98-1
    executor:
      name: cypress/default
      node-version: '20.14.0'
    environment:
      CYPRESS_DEFAULT_EMAIL: $DEFAULT_EMAIL
      CYPRESS_DEFAULT_PASSWORD: $DEFAULT_PASSWORD
    steps:
      - cypress/install
      - cypress/run-tests:
          cypress-command: 'npx wait-on@latest http://localhost:3000 && npx cypress run'
          start-command: 'npm run build && npm run start'

workflows:
  build:
    jobs:
      - cypress-run
