version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    executor:
      name: cypress/default
      node-version: '20.14.0'
    steps:
      - checkout
      - run:
          name: 'Build and Start Application'
          command: |
            npm run build
            npm run start &
      - run:
          name: 'Wait for App & Run Cypress Tests'
          command: |
            npx wait-on@latest http://localhost:3000
            env_string=$(printenv | grep '^CYPRESS_' | paste -sd, -)
            echo "Using env: $env_string"
            npx cypress run --env $env_string

workflows:
  build:
    jobs:
      - cypress-run
