version: 2.1
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  cypress-run:
    executor:
      name: cypress/default
      node-version: '20.14.0'
    steps:
      - checkout
      - cypress/install
      - run:
          name: 'Prepare env string'
          command: |
            env_string=$(printenv | grep '^CYPRESS_' | paste -sd, -)
            echo "$env_string" > env_string.txt
            echo "Using env: $env_string"
      - cypress/run-tests:
          cypress-command: >
            npx wait-on@latest http://localhost:3000 &&
            npx cypress run --env $(cat env_string.txt)
          start-command: 'npm run build && npm run start'

workflows:
  build:
    jobs:
      - cypress-run
